<?php
/**
 * @file
 * vp_wysiwyg_add_row.features.wysiwyg_template.inc
 */

/**
 * Implements hook_wysiwyg_template_default_templates().
 */
function vp_wysiwyg_add_row_wysiwyg_template_default_templates() {
  $templates = array();
  $templates['hall_taust_3_veergu'] = array(
    'title' => 'Hall taust - 3 veergu - lisa rida',
    'description' => '',
    'weight' => 21,
    'fid' => 0,
    'body' => '<div class="static static-textblock-gray-background-add-row">
	<h2>Selgituseks</h2>
	<p>Paar rida selgitavat teksti, et misasi on “selgituseks” plokk. Paar rida selgitavat teksti, et misasi on “selgituseks” plokk.Paar rida selgitavat teksti, et misasi on “selgituseks” plokk.Paar rida selgitavat teksti, et misasi on “selgituseks” plokk.Paar rida selgitavat teksti, et misasi on “selgituseks” plokk.</p>
	<div class="container-12">
		<div class="textbox grid-4">
			<div class="textbox-inner">
				<h3>Mis on OECD?</h3>
				<p><strong>OECD ehk Majandusliku Koostöö ja Arengu Organisatsioon (inglise keeles Organisation for Economic Co-operation and Development) on tööstuslikult arenenud demokraatlike riikide foorum alalise asukohaga Pariisis. OECDsse kuulub hetkel 34 riiki.</strong></p>
				<p>Organisatsiooni eesmärk on aidata kaasa maailmamajanduse arengule, samuti ka liikmes- ja mitteliikmesriikide majandusarengule ning maailmakaubanduse laienemisele. OECD peamised tegevusvaldkonnad on liikmesriikide majandusnäitajate kogumine ja analüüsimine ning soovituste andmine, et riigid saaksid oma majanduspoliitikat tulemuslikumalt kujundada. Samuti tegeleb OECD sotsiaalsete ja keskkonnakaitse probleemide analüüsimise ning nende ennetamisega. Mitte ajada segi OSCEga, mis on Euroopa Julgeoleku- ja Koostööorganisatsioon (inglise keeles Organization for Security and Co-operation in Europe)</p>
			</div>
		</div>
		<div class="textbox grid-4">
			<div class="textbox-inner">
				<h3>Mis on OECD?</h3>
				<p><strong>OECD ehk Majandusliku Koostöö ja Arengu Organisatsioon (inglise keeles Organisation for Economic Co-operation and Development) on tööstuslikult arenenud demokraatlike riikide foorum alalise asukohaga Pariisis. OECDsse kuulub hetkel 34 riiki.</strong></p>
				<p>Organisatsiooni eesmärk on aidata kaasa maailmamajanduse arengule, samuti ka liikmes- ja mitteliikmesriikide majandusarengule ning maailmakaubanduse laienemisele. OECD peamised tegevusvaldkonnad on liikmesriikide majandusnäitajate kogumine ja analüüsimine ning soovituste andmine, et riigid saaksid oma majanduspoliitikat tulemuslikumalt kujundada. Samuti tegeleb OECD sotsiaalsete ja keskkonnakaitse probleemide analüüsimise ning nende ennetamisega.</p>
			</div>
		</div>
		<div class="textbox grid-4">
			<div class="textbox-inner">
				<h3>Mis on OECD?</h3>
				<p><strong>OECD ehk Majandusliku Koostöö ja Arengu Organisatsioon (inglise keeles Organisation for Economic Co-operation and Development) on tööstuslikult arenenud demokraatlike riikide foorum alalise asukohaga Pariisis. OECDsse kuulub hetkel 34 riiki.</strong></p>
				<p>Organisatsiooni eesmärk on aidata kaasa maailmamajanduse arengule, samuti ka liikmes- ja mitteliikmesriikide majandusarengule ning maailmakaubanduse laienemisele. OECD peamised tegevusvaldkonnad on liikmesriikide majandusnäitajate kogumine ja analüüsimine ning soovituste andmine, et riigid saaksid oma majanduspoliitikat tulemuslikumalt kujundada. Samuti tegeleb OECD sotsiaalsete ja keskkonnakaitse probleemide analüüsimise ning nende ennetamisega.</p>
			</div>
		</div>
	</div>
	<div class="add-row"><input class="add-row" id="add-button" name="add" type="button" value="Lisa rida"></div>
</div>
<p>&nbsp;</p>
',
    'name' => 'hall_taust_3_veergu',
    'content_types' => array(),
  );
  $templates['static_module_3_2_add_row'] = array(
    'title' => '3 veergu - taustaga - lisa rida',
    'description' => '',
    'weight' => 20,
    'fid' => 0,
    'body' => '<div class="static-module-3-2-add-row clearfix">
	<h2>Küsimused ja Vastused</h2>
	<div class="row">
		<div class="col col-1">
			<h3>Kas ma võin jääda elektrita, kui midagi ette ei võta?</h3>
			<p>Ei - ühegi kodu ega ettevõtte varustamine elektriga ei katke hetkekski ning elektrimüüjat saab igaüks vahetada ka pärast turu avanemist kasvõi igal kuul. Neid tarbijad, kes ei soovi või ei jõua enne 2013. aastat elektrimüüjat valida, varustab elektrienergiaga asjaomase piirkonna võrguettevõtja üldteenuse raames. See tähendab, et hinna aluseks on eelmise kuu kaalutud keskmine börsihind, millele lisandub ettevõtte mõistlik kasum. Ettevõtete kasumimarginaal on Konkurentsiameti pideva vaatluse all.</p>
		</div>
		<div class="col col-2">
			<h3>Kas ma võin jääda elektrita, kui midagi ette ei võta?</h3>
			<p>Ei - ühegi kodu ega ettevõtte varustamine elektriga ei katke hetkekski ning elektrimüüjat saab igaüks vahetada ka pärast turu avanemist kasvõi igal kuul. Neid tarbijad, kes ei soovi või ei jõua enne 2013. aastat elektrimüüjat valida, varustab elektrienergiaga asjaomase piirkonna võrguettevõtja üldteenuse raames.</p>
			<p>See tähendab, et hinna aluseks on eelmise kuu kaalutud keskmine börsihind, millele lisandub ettevõtte mõistlik kasum. Ettevõtete kasumimarginaal on Konkurentsiameti pideva vaatluse all.</p>
		</div>
		<div class="col col-3 last">
			<h3>Kas ma võin jääda elektrita, kui midagi ette ei võta?</h3>
			<p>Ei - ühegi kodu ega ettevõtte varustamine elektriga ei katke hetkekski ning elektrimüüjat saab igaüks vahetada ka pärast turu avanemist kasvõi igal kuul. Neid tarbijad, kes ei soovi või ei jõua enne 2013. aastat elektrimüüjat valida, varustab elektrienergiaga asjaomase piirkonna võrguettevõtja üldteenuse raames. See tähendab, et hinna aluseks on eelmise kuu kaalutud keskmine börsihind, millele lisandub ettevõtte mõistlik kasum. Ettevõtete kasumimarginaal on Konkurentsiameti pideva vaatluse all.</p>
		</div>
	</div>
	<div class="add-row"><input class="add-row" id="add-button" name="add" type="button" value="Lisa rida"></div>
</div>
<p>&nbsp;</p>
',
    'name' => 'static_module_3_2_add_row',
    'content_types' => array(),
  );
  return $templates;
}
