<?php

/**
 * @file
 * Riigikantselei abimoodul. css / js, mis ei ole vp pakettis.
 * Märt Matsoo. mart@matsoo.com.
 */


/**
 * Implementation of hook_init().
 */
function rk_abi_init() {

  // Load css.
  drupal_add_css(drupal_get_path('module', 'rk_abi') . '/css/rk_abi.css');

  // Load js.
  drupal_add_js(drupal_get_path('module', 'rk_abi') . '/js/rk_abi.js', array('scope' => 'footer', 'weight' => 10));

  //drupal_add_js('jQuery(document).ready(function () { var S5 = "do this and do that";//alert(S5); });', array('type' => 'inline', 'scope' => 'header'));

}


/**
 * Implementation of hook_permission().
 */
function rk_abi_permission() {

  $perms = array(
    'admin riigikantselei abimoodul' => array(
      'title' => t('Administer Riigikantselei Helper Module'),
      'description' => t('Full administrator access for Riigikantselei Helper Module.'),
      'restrict access' => FALSE,
    ),
  );

  return $perms;

}


/**
 * Implementation of hook_menu().
 */
function rk_abi_menu() {

  $items = array();

  $items['admin/config/rkabi'] = array(
    'title' => 'Riigikantselei Abimoodul',
    'access arguments' => array('admin riigikantselei abimoodul'),
    'position' => 'right',
    'weight' => 49,
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/rkabi/settings'] = array(
    'title' => 'Riigikantselei Abimoodul Settings',
    'description' => t('General settings form'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rk_abi_settings'),
    'access arguments' => array('admin riigikantselei abimoodul'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
  );

  return $items;
}


/**
 * Form builder for general settings form.
 */
function rk_abi_settings($form, &$form_state) {

  $form = array();

  $form['rk_abi_contact_email_obfuscate'] = array(
    '#type' => 'checkbox',
    '#title' => t('Obfuscate emails on Contact pages'),
    '#default_value' => variable_get('rk_abi_contact_email_obfuscate', 0),
    '#description' => t('The contact views output needs to be plain text, not email link for this to work.'),
  );

  $form['rk_abi_newsletter_use_social_media_insert_block'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use social media footer block in newsletters'),
    '#default_value' => variable_get('rk_abi_newsletter_use_social_media_insert_block', 0),
    '#description' => t('Turn on/off the insertion of this block at the bottom of newsletters.'),
  );

  $form['rk_abi_newsletter_social_media_insert'] = array(
    '#type' => 'textfield',
    '#title' => t('Block ID of social media footer block'),
    '#default_value' => variable_get('rk_abi_newsletter_social_media_insert', 0),
    '#description' => t('This block can be created and used in the footer of press releases and other newsletters. You can use it to include links to Facebook, Twitter etc. You have to create this block by hand. Blocks are found at Structure -> Blocks. The Block ID is the 2nd last (often integer) value in the URL when you hover over the block\'s "configure" link. Ex. The number "14" in admin/structure/block/manage/block/<strong><u>14</u></strong>/configure'),
  );  

  return system_settings_form($form);
}


/**
 * Implements hook_preprocess_html().
 */
function rk_abi_preprocess_html(&$variables) {

  // Get domain name from http_host variable.
  $arrDomain = explode('.', $_SERVER['HTTP_HOST']);
  $index = sizeof($arrDomain) - 2;

  // Add domain (ex. riigikantselei) to body classes. We can hook off it to apply styles to specific sites.
  $variables['classes_array'][] = $arrDomain[$index];
}


/**
 * Abifunktsioon, obfuscate e-postid.
 * Siit: http://www.maurits.vdschee.nl/php_hide_email/
 */
function _rk_peida_email($email) { 
  $character_set = '+-.0123456789@ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz';
  $key = str_shuffle($character_set); $cipher_text = ''; $id = 'e'.rand(1,999999999);

  for ($i=0;$i<strlen($email);$i+=1) $cipher_text.= $key[strpos($character_set,$email[$i])];
  $script = 'var a="'.$key.'";var b=a.split("").sort().join("");var c="'.$cipher_text.'";var d="";';
  $script.= 'for(var e=0;e<c.length;e++)d+=b.charAt(a.indexOf(c.charAt(e)));';
  $script.= 'document.getElementById("'.$id.'").innerHTML="<a href=\\"mailto:"+d+"\\">"+d+"</a>"';
  $script = "eval(\"".str_replace(array("\\",'"'),array("\\\\",'\"'), $script)."\")"; 
  $script = '<script type="text/javascript">/*<![CDATA[*/'.$script.'/*]]>*/</script>';
  return '<span id="'.$id.'">[javascript protected email address]</span>'.$script;

}  


/**
 * Implements hook_filter_info_alter().
 *
 * Perform alterations on filter definitions.
 *
 * @param $info
 *   Array of information on filters exposed by hook_filter_info()
 *   implementations.
 */
function rk_abi_filter_info_alter(&$info) {
  // Check for evidence of simplenews and turn off regular email obfuscation. Ex. node/3745/simplenews
  if (arg(0) == 'node' && arg(2) == 'simplenews') {
    $info['geo_filter_filter']['process callback'] = 'rk_abi_plain_text_email';
  }
}


/**
 * Do not want geo_filter obfuscated emails in newsletters.
 * Called from rk_abi_filter_info_alter when simplenews has been detected.
 * Just returning text without any filtering.
 */
function rk_abi_plain_text_email($text, $filter, $format, $langcode, $cache, $cache_id) {
  return $text;
}