<?php

/**
 * Implements hook_menu().
 */
function vp_migrate_menu() {
  $items = array();
 
  $items['admin/structure/migrate-db'] = array(
    'title' => 'Migrate database settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vp_migrate_page', NULL),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
 
  return $items;
}
 
/**
 * Migrate database settings administration form.
 */
function vp_migrate_page() {
  $form = array();
 
  $form['vp_migrate_database'] = array(
    '#type' => 'textfield', 
    '#title' => t('Database'), 
    '#default_value' => variable_get('vp_migrate_database', ''),
  );
  
  $form['vp_migrate_username'] = array(
    '#type' => 'textfield', 
    '#title' => t('Username'), 
    '#default_value' => variable_get('vp_migrate_username', ''),
  );
  
  $form['vp_migrate_password'] = array(
    '#type' => 'textfield', 
    '#title' => t('Password'), 
    '#default_value' => variable_get('vp_migrate_password', ''),
  );
  
  $form['vp_migrate_host'] = array(
    '#type' => 'textfield', 
    '#title' => t('Host'), 
    '#default_value' => variable_get('vp_migrate_host', ''),
  );
 
  return system_settings_form($form);
}
