<?php
/**
 * @file
 * vp_core.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function vp_core_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Rahandusministeerium',
    'description' => '',
    'format' => 'full_html',
    'weight' => 3,
    'uuid' => '5474c52d-c83b-4751-9059-a424a6532e7e',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Siseministeerium',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5dbe5415-2162-420c-88a4-d3b511676d4a',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Haridus- ja teadusministeerium',
    'description' => NULL,
    'format' => NULL,
    'weight' => 5,
    'uuid' => '6316f139-c00a-4627-ac23-5ee2210125a7',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Keskkonnaministeerium',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '7bad541b-de3f-41f1-89d1-eb68c460cd30',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Sotsiaalministeerium',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '7dad8401-6d10-4608-a914-05a538bb8ea0',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Government Office',
    'description' => '',
    'format' => 'full_html',
    'weight' => 4,
    'uuid' => '83bc3d33-245c-49d5-a314-1c0bdb40fda8',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Kaitseministeerium',
    'description' => '',
    'format' => 'full_html',
    'weight' => 2,
    'uuid' => '9ae81fca-b7f4-4f42-987e-66e1b64f7964',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Justiitsministeerium',
    'description' => '',
    'format' => 'full_html',
    'weight' => 1,
    'uuid' => '9d4f1225-0986-402a-9974-9b40c5251146',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Vabariigi Valitsus',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '9fab9218-e732-4122-9e07-ee656e19eedf',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Põllumajandusministeerium',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b57f10cb-a661-4ebe-8004-b106f8fa7935',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Foreign Ministry',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'cd87fc74-5918-4a54-819e-ce5ced727370',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Majandus- ja Kommunikatsiooniministeerium',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd929fb93-5c94-4544-ab85-6141ac4fd71c',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Kultuuriministeerium',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e7e745a5-684e-4f01-9008-949fd75a24eb',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'source',
    'url_alias' => array(),
  );
  return $terms;
}
