<?php

/**
 * @file
 *
 */

/**
 * Implements hook_views_pre_view().
 */
function vp_gallery_views_pre_view(&$view, &$display_id, &$args) {
  if ($view->name == 'vp_galleries') {
    vp_gallery_add_retina_js();
    if (isset($_GET['keyword'])) {
      $_GET['body'] = $_GET['keyword'];
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function vp_gallery_views_query_alter(&$view, &$query) {
  if ($view->name == 'vp_galleries' && isset($_GET['body']) && !empty($_GET['body'])) {
    $query->where[2]['conditions'][1]['value'] = '%' . $_GET['body'] . '%';
  }
}


/**
 * Implements hook_node_view().
 */
function vp_gallery_node_view($node, $view_mode, $langcode) {
  if ($node->type === 'gallery') {
    vp_gallery_add_retina_js();
  }
}

function vp_gallery_add_retina_js() {
  drupal_add_js(drupal_get_path('module', 'vp_gallery') .'/js/retina.js', array('scope' => 'footer'));
}

/**
 * Implements hook_node_presave().
 * When picture don't have alt text then gallery title added to the picture alt text field.
 */
function vp_gallery_node_presave($node) {
  if ($node->type == "gallery"){
    $title = $node->title;
    foreach( $node->field_pictures[LANGUAGE_NONE] as $gallery ) {
      if ($gallery['field_picture'][LANGUAGE_NONE][0]['alt'] == NULL){
        if ($gallery['field_title'][LANGUAGE_NONE][0]['value'] != NULL) {
          $gallery['entity']->field_picture[LANGUAGE_NONE][0]['alt'] = $gallery['field_title'][LANGUAGE_NONE][0]['value'];
        }
        else {
          $gallery['entity']->field_picture[LANGUAGE_NONE][0]['alt'] = $title;
        }
      }
    }
  }
}