<?php
/**
 * @file
 * vp_news.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function vp_news_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Education and Science',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1fe64497-90a5-45a2-8f6b-780fd95b980c',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Sport',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '20206a08-8048-49a3-91e3-45089a32143a',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Transport',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '23afef92-ea7d-41f6-b040-78c11e123e4f',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Economy',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '249702c6-f0c3-43c9-a493-59f95efd30a6',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Civil Society',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '29302c3c-85af-44d0-8d5a-8b86828f2300',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Session schedule',
    'description' => '',
    'format' => 'full_html',
    'weight' => 5,
    'uuid' => '2f863e4a-8e3b-42bd-8101-fcb9c8b1e195',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_types',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Press release',
    'description' => '',
    'format' => 'full_html',
    'weight' => 6,
    'uuid' => '42c3807a-68ec-4fc2-a17c-0c2b82c0c1f4',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_types',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Foreign Policy',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '49a92254-132c-4298-9835-e47119e2f0a8',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Short announcement',
    'description' => '',
    'format' => 'full_html',
    'weight' => 2,
    'uuid' => '4fefa6e2-4141-4f87-84f4-b3603369786a',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_types',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'From session',
    'description' => '',
    'format' => 'full_html',
    'weight' => 4,
    'uuid' => '56338c18-3357-448a-9e07-3fdbff3883ea',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_types',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Culture',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '594bbc4c-2048-475c-908c-8891032e8927',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Integration',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '603efa2f-99cc-4eda-81d1-644548aa2988',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Families and Population',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '61c4431e-13bc-41b4-aecb-6469181c7893',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Agriculture',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8ab3ff66-7461-4983-9dc4-dbfb36ec78d9',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Important',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8c3eb7f0-4f50-4cd6-950e-759a7c47a686',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_types',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Information Society',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '94ed5abe-bf1c-4f0d-8ec8-7147019afcb5',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Energetics',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b109aecd-8b69-42a6-8dc6-89bb721ad40c',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Cabinet meeting',
    'description' => '',
    'format' => 'full_html',
    'weight' => 1,
    'uuid' => 'bf8c911b-177c-4530-af96-969845dbfa1b',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_types',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'National Defence',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd4d837f9-accc-42ac-b06b-0f6363f2aaff',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Internal security',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd56557ea-3e11-46cc-aeb6-61698e367ccc',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Estonian language',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'db310748-de44-4068-873b-17fa3a3797c4',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Stenogram',
    'description' => '',
    'format' => 'full_html',
    'weight' => 3,
    'uuid' => 'ea9c1f03-d5f0-4afe-8c56-66b5cb48209b',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_types',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Working',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ede0f46d-7768-4172-b267-6a0439acb784',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Health Care',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ef042e01-99b7-4ea3-bbe1-fc70c7bfe422',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Environment',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f19cc169-daff-4184-a656-0853bf5fb5de',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'news_subjects',
    'url_alias' => array(),
  );
  return $terms;
}
