<?php

/**
 * Implementation of hook_menu().
 */
function xmltax_menu() {
  $items = array();

	$items['xmltax'] = array(
		'title' => t('Vocab / Taxonomy XML output'),
		'description' => t('Create XML output of vocabulary / taxonomies'),
		'page callback' => 'xmltax_build',
    'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

  return $items;
}

/**
 * create the XML output
 */
function xmltax_build() {
  global $language;
  $vocabularies = taxonomy_get_vocabularies();

  echo '<?xml version="1.0" ?>'."\n";
  echo '<vocabularies>' . "\n";

	foreach ($vocabularies as $vid => $vocabulary) {

    if ($vocabulary->vid != 7 && $vocabulary->vid != 3) {
		  echo '<vocabulary>'."\n";
		  echo '  <vid>' . $vid . '</vid>' . "\n";
		  echo '  <name>' . $vocabulary->name . '</name>' . "\n\n";
		  echo '  <terms>' . "\n\n";

			$options = taxonomy_get_tree($vocabulary->vid);

				foreach ($options as $key => $value) {
          $parent = $value->parents[0];
          $value = i18n_taxonomy_localize_terms(taxonomy_term_load($value->tid));
				  echo '  <term>' . "\n";
				  echo '    <name>' . t($value->name) . '</name>' . "\n";
				  echo '    <link>http://www.vm.ee/?q=' . $language->language . '/taxonomy/term/' . $value->tid . '/feed</link>' . "\n";
				  echo '    <tid>' . $value->tid . '</tid>' . "\n";
				  echo '    <vid>' . $value->vid . '</vid>' . "\n";
				  echo '    <language>' . $language->language . '</language>' . "\n";
				  echo '    <parent_tids>' . $parent . '</parent_tids>' . "\n";
				  echo '  </term>' . "\n\n";
				}
		  echo '</terms>' . "\n" . '</vocabulary>' . "\n\n\n";
    }
	}

  echo '</vocabularies>' . "\n";

  drupal_exit();
}
