<?php

/**
 * @file
 * Feeds SOAP Fetcher - SOAP fetcher for Feeds.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function feeds_soap_fetcher_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function feeds_soap_fetcher_ctools_plugin_type() {
  return array(
    'plugins' => array(
      'cache' => TRUE,
      'use hooks' => TRUE,
      'classes' => array('handler'),
    ),
  );
}

/**
 * Implementation of hook_feeds_plugins().
 */
function feeds_soap_fetcher_feeds_plugins() {
  $info = array();

  $info['FeedsSOAPFetcher'] = array(
    'name' => 'SOAP Fetcher',
    'description' => 'Fetches a SOAP feed.',
    'handler' => array(
      'parent' => 'FeedsFetcher',
      'class' => 'FeedsSOAPFetcher',
      'file' => 'FeedsSOAPFetcher.inc',
      'path' => drupal_get_path('module', 'feeds_soap') . '/plugins',
    ),
  );

  return $info;
}
